[ssh]
host = 127.0.0.1
port = 22
username = ...
password = ...

[paths]
remote_dir = ~/
remote_tar = ~/backup.tar.gz
local_tar = backup.tar.gz

[discord]
; REQUIRED: ID of the Discord server (guild) where you want to create the A/D category
; To get this:
; 1) Enable Developer Mode in Discord (Settings -> Advanced)
; 2) Right-click the server name -> "Copy Server ID"
guild_id = ...