[ssh]
host = 127.0.0.1
port = 22
username = ...
password = ...

[paths]
remote_dir = ~/
remote_zip = ~/backup.zip
local_zip = backup.zip

[discord]
; REQUIRED: ID of the Discord server (guild) where you want to create the A/D category
; To get this:
; 1) Enable Developer Mode in Discord (Settings -> Advanced)
; 2) Right-click the server name -> "Copy Server ID"
guild_id = ...


[git]
repo_name = AD-snapshot
commit_message = Initial AD snapshot
visibility = private
collaborators = ... # Seperate by ,